routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/instructivo', function () {
    return view('admin.instructivo');
});

Auth::routes();

//Route::get('/admin', 'PrincipalController@index');
Route::get('/admin', ['as' => 'admin', 'uses' => 'PrincipalController@index']);
Route::get('/admin/productos/get_data_productos', ['as' => 'get_data_productos', 'uses' => 'ProductosController@get_data']);
Route::get('/admin/categorias/get_data_categorias', ['as' => 'get_data_categorias', 'uses' => 'CategoriasController@get_data']);
Route::get('/admin/tipos/get_data_tipos', ['as' => 'get_data_tipos', 'uses' =>'TiposController@get_data']);
Route::get('/admin/marcas/get_data_marcas', ['as' => 'get_data_marcas', 'uses' =>'MarcasController@get_data']);

//Route::get('/admin/productos/{id}/upload', ['as' => 'upload_img', 'uses' =>'ImgProductoController@index']);
//Route::get('/admin/img_remove', ['as' => 'remove_img', 'uses' =>'ImgProductoController@delete']);
//Route::post('/admin/img_upload', ['as' => 'upload', 'uses' =>'ImgProductoController@upload']);
Route::resource('/admin/productos', 'ProductosController');
Route::resource('/admin/categorias', 'CategoriasController');
Route::resource('/admin/marcas', 'MarcasController');
Route::resource('/admin/tipos', 'TiposController');

resources/views/admin/addimgproducto.blade.php
@extends('layouts.admin')

@section('content')
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="title-block">
        <h3 class="title"> Agregue una imágen al Producto {{$prod->codigo}}<span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <div class="card card-block">
        <div class="form-group row">
            <label class="col-sm-1 form-control-label text-xs-right">
                Imagenes:
            </label>
            <div class="col-sm-10">
                <div class="card card-block filepicker" id="dz-area">
                    <form  enctype="multipart/form-data" class="dropzone" id="imgDropzone" name="producto" method="POST" action="{{ route('upload') }}">
                        {{ csrf_field() }}
                        <div class="dz-message-block">
                            <div class="dz-message needsclick"> Arrastre la imágen aquí o haga click para abrir el selector.</div>
                        </div>
                        <div class="dropzone-previews" id="preview"></div>
                         <div class="fallback">
                        <input type="hidden" name="id_prod" id="id_prod" value="{{$prod->id}}">
                    </form>
                </div>
            </div>
        </div>
        <div class="row pull-right">
            <div class="col-sm-12"> <button type="submit" class="btn btn-primary" id="btn_guardar">
                Guardar
                </button> 
            </div>
        </div>
    </div>
@endsection

resources/views/admin/addproductos.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('css/component.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="title-block">
        <h3 class="title"> Agregue un Nuevo Producto <span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <form id="add_product" name="producto" method="POST" enctype="multipart/form-data" action="{{ route('productos.store') }}">
        {{ csrf_field() }}
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Categoría:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="categoria">
                        <option selected>Seleccione Categoría</option>
                        @foreach($categorias as $cat)
                            <option value="{{$cat->id}}">{{$cat->categoria}}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                Tipo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="tipo">
                        <option selected>Seleccione Tipo</option>
                        @foreach($tipos as $tipo)
                            <option value="{{$tipo->id}}">{{$tipo->tipo}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Marca:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="marca">
                        <option selected>Seleccione Marca</option>
                        @foreach($marcas as $mar)
                            <option value="{{$mar->id}}">{{$mar->marca}}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Código:
                </label>
                <div class="col-sm-3"> <input type="text" class="form-control boxed" name="codigo" id="codigo" value=""> </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Descripción:
                </label>
                <div class="col-sm-10">
                    <textarea id="mytextarea" name="descripcion"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Imágen:
                </label>
                <div class="col-sm-10">
                    <div class="box js">
                        <input type="file" name="imagen" id="file-7" class="inputfile inputfile-6" accept="image/*" onchange="readURL(this);"/>
                        <label for="file-7"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Seleccione Imágen&hellip;</strong></label>
                        <img id="preview" src="#" alt="" />
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12"> <button type="submit" class="btn btn-primary" id="btn_guardar">
                    Guardar
                    </button> 
                </div>
            </div>
        </div>
    </form>
@endsection

@section('mensajes')
    <?php $message=Session::get('message')?>
    @if($message != '')
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @if($message == 'producto_add')
                Producto Ingresado con exito.
            @endif
        </div>
    @endif
@endsection

@section('scripts')
    <script src="{{asset ('vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset ('js/jquery.custom-file-input.js')}}"></script>
    <script src="{{asset ('js/textEditor_Image_cfg.js')}}"></script>
@endsection

resources/views/admin/editproductos.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('css/component.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="title-block">
        <h3 class="title"> Editar Producto {{$producto->codigo}}<span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <form id="edit_product" name="producto" enctype="multipart/form-data" action="{{route('productos.update', 'editar')}}" method="post">
        {{method_field('patch')}}
        {{csrf_field()}}
    <input type="hidden" name="producto_id" id="producto_id" value="{{$producto->id}}">
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Categoría:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="categoria" id="categoria">
                        @foreach($categorias as $cat)
                            <option value="{{$cat->id}}">{{$cat->categoria}}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                Tipo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="tipo" id="tipo">
                        @foreach($tipos as $tipo)
                            <option value="{{$tipo->id}}">{{$tipo->tipo}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Marca:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="marca" id="marca">
                        @foreach($marcas as $mar)
                            <option value="{{$mar->id}}">{{$mar->marca}}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Código:
                </label>
            <div class="col-sm-3"> <input type="text" class="form-control boxed" name="codigo" id="codigo" value="{{$producto->codigo}}"> </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                Descripción:
                </label>
                <div class="col-sm-10">
                <textarea id="mytextarea" name="descripcion">{{$producto->descripcion}}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Imágen:
                </label>
                <div class="col-sm-10">
                    <div class="box js">
                        <input type="file" name="imagen" id="file-7" class="inputfile inputfile-6" accept="image/*" oninput="readURL(this)"/>
                    <label for="file-7"><span>{{$imageName}}</span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Seleccione Imágen&hellip;</strong></label>
                    <img id="preview" src="#" alt="" />
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12"> <button type="submit" class="btn btn-primary" id="btn_guardar">
                    Guardar
                    </button> 
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
        var valorSeleccionado = {
                'categoria': '{{$producto->categoria_id}}',
                'tipo': '{{$producto->tipo_id}}',
                'marca': '{{$producto->marca_id}}',
                'image': '{{$image}}',
            };
    </script>
    <script src="{{asset ('js/valueSetter.js')}}"></script>
    <script src="{{asset ('vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset ('js/jquery.custom-file-input.js')}}"></script>
    <script src="{{asset ('js/textEditor_Image_cfg.js')}}"></script>
@endsection

resources/views/admin/instructivo.blade.php
@extends('layouts.admin')

@section('content')
    <article class="content dashboard-page">
        <section class="section">
            <div class="row">
                <div class="col col-md-4">
                    <div class="card">
                        <h1>Instrucciones</h1>
                    </div>
                </div>                
            </div>
        </section>
    </article>
@endsection

resources/views/admin/principal.blade.php
@extends('layouts.admin')

@section('content')
    <div class="title-block">
        <h1 class="title"> Productos </h1>
        <p class="title-description"> Lista de productos en el sistema </p>
    </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-block">
                        <table class="table table-bordered table-hover" id="productos-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Imágen</th>
                                    <th>Código</th>
                                    <th>Categoría</th>
                                    <th>Tipo</th>
                                    <th>Descripción</th>
                                    <th>Marca/Modelo</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 center-block">
                <div class="title-block title-margin">
                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <h1 class="title"> Categorías </h1>
                            <p class="title-description"> Lista de categorías </p>
                        </div>
                        <div class="col-md-6">
                            <button type="button" id="agregar" class="btn btn-primary pull-right" data-toggle="modal" data-target="#add-categoria-modal">
                                <i class="fa fa-plus"></i>
                                Agregar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 center-block">
                <div class="title-block title-margin">
                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <h1 class="title"> Tipos </h1>
                            <p class="title-description"> Lista de los tipos de producto</p>
                        </div>
                        <div class="col-md-6">
                            <button type="button" id="agregar" class="btn btn-primary pull-right" data-toggle="modal" data-target="#add-tipo-modal">
                                <i class="fa fa-plus"></i>
                                Agregar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 center-block">
                <div class="card">
                    <div class="card-block">
                        <table class="table table-bordered table-hover" id="categorias-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Categoría</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-5 center-block">
                <div class="card">
                    <div class="card-block">
                        <table class="table table-bordered table-hover" id="tipos-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Tipo</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 center-block">
                <div class="title-block title-margin">
                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <h1 class="title"> Marcas/Modelos </h1>
                            <p class="title-description"> Lista de marcas/modelos </p>
                        </div>
                        <div class="col-md-6">
                            <button type="button" id="agregar" class="btn btn-primary pull-right" data-toggle="modal" data-target="#add-marca-modal">
                                <i class="fa fa-plus"></i>
                                Agregar
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-block">
                        <table class="table table-bordered table-hover" id="marcas-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Marca/Modelo</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
@endsection

@section('scripts')
    <script src="{{asset ('js/modal-delete.js')}}"></script>
    <script src="{{asset ('js/tables.js')}}"></script>
@endsection

@include('admin.modals')

resources/views/admin/principal2.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h1>Acá va algún menu</h1>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection